### PR TITLE
preventing rapidfire click action

### LINKED ISSUE #586: Transitions between linked pages broken if you act quickly (?)
Not sure how to phrase this one properly. Can make the browser player act really jumpy and improperly though:
1. Check out https://beta.webmaker.org/#/project?user=452666&project=5218
2. Click on button on first page.
3. Click on button on second page.
4. Click on button on third page.
5. Quickly click on first page button again.

Eventually, this will cause some strange transitions for me — like jumping between 1 & 3.

Here's a video of me having a whole bunch of trouble with those buttons: https://dl.dropboxusercontent.com/u/7054348/webmaker-buttons-bug.mov

Generally, trying to quickly click on buttons makes problems. Unable to click buttons again, flickering between pages, etc. Maybe something to do with the page transition not completing.

### PR DESCRIPTION
**Pull request by gvn**
Closes #586

### CODE REVIEW

File: src/pages/project/cartzoom.js [hunk 1]
```diff
@@ -143,6 +165,17 @@ module.exports = {
         }
       });
     }
+
+    var elBounding = this.refs.bounding.getDOMNode();
+
+    // Turn off animation flag (used to block interactions)
+    elBounding.addEventListener('transitionend', (event) => {
```
Comment (k88hudson) [inline src/pages/project/cartzoom.js:172]: This will break on Safari, IE for the player; you will need to do detection of which `transitionend` event to listen for (alternatively, you could use a timeout). Also, this will be a 100% breaking experience for browsers that don't support CSS transitions -- are we OK with that?

File: src/pages/project/cartzoom.js [hunk 2]
```diff
@@ -143,6 +165,17 @@ module.exports = {
...
+      if (event.propertyName === 'transform' || event.propertyName === '-webkit-transform') {
```
Comment (gvn) [inline src/pages/project/cartzoom.js:173]: This additional prefix check should fix it...

**Comment by gvn** [comment]
AFAIK we're not supporting below IE10, so we should be good for transition support...

http://caniuse.com/#search=transitions

**Comment by k88hudson** [comment]
Ok, looks good
