### PR TITLE
Make Tinker color changes more apparent

### LINKED ISSUE #906: Text element background tinker color starts with zero opactiy
If a user taps tinker when no previous background color is selected, it seems like the color picker doesn't work, because opacity is set to zero. It should default to 1. Background color default can be set to 'none' to avoid need for zero opacity.

### PR DESCRIPTION
**Pull request by alanmoo**
When opacity is zero and an attempt is made at changing the color, opacity will be forced back to 1. Closes #906

### CODE REVIEW

File: src/pages/tinker/tinker.jsx [hunk 1]
```diff
@@ -172,12 +173,19 @@ var Tinker = React.createClass({
...
     edits[this.state.params.propertyName] = value.rgbaString();
     this.setState({
       element: assign({}, this.state.element, edits)
     });
   },
-
+  preventInvisibleColors: function(value) {
+    var currentColor = Color(this.state.element.color).values;
+    var nextColor = value.values;
+    if(currentColor.alpha == 0 && nextColor.alpha == 0){
```
Comment (gvn) [inline src/pages/tinker/tinker.jsx]: Any reason not to use `===`?

Comment (alanmoo) [inline src/pages/tinker/tinker.jsx]: I was being cautious in the event it somehow gets handed a string.

Comment (alanmoo) [inline src/pages/tinker/tinker.jsx]: Though since it's coming from the Color module, that's highly unlikely. I'll change it.
